apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - crystolia.com
        - www.crystolia.com
        - crystolia.co.il
        - www.crystolia.co.il
      secretName: crystolia-tls
  rules:
    - host: crystolia.com
      http: &http_rules
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 3000
    - host: www.crystolia.com
      http: *http_rules
    - host: crystolia.co.il
      http: *http_rules
    - host: www.crystolia.co.il
      http: *http_rules
