apiVersion: v2
name: crystolia-chart
description: A Helm chart for the Crystolia DevOps Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "56.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"

