# Default values for crystolia-chart.

global:
  environment: "development"

frontend:
  image:
    repository: shaimullo/crystolia-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  replicaCount: 1

backend:
  image:
    repository: shaimullo/crystolia-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  replicaCount: 1
  env:
    MONGO_URI: "mongodb://mongo:27017/crystolia"
    FRONTEND_URL: "http://a6642f379b69541168bf4514fd4f291d-1331101001.us-east-1.elb.amazonaws.com"
    GOOGLE_CLIENT_ID: "42819184159-tqh018b0d0dkhv6sc37abov9rmjkgaer.apps.googleusercontent.com"
    GOOGLE_CLIENT_SECRET: "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"
    JWT_SECRET: "crystolia-super-secret-jwt-key-2026"

mongodb:
  image:
    repository: mongo
    tag: 6.0
  service:
    port: 27017
  persistence:
    enabled: true
    size: 1Gi
